### PR TITLE
Feature/mailer integration

### PR DESCRIPTION
**Pull request by wipascal**
no new functionality, just moving code from the urbanmosaic repo to basxconnect

### CODE REVIEW

**Review by saemideluxe — CHANGES_REQUESTED** [review]
1. We should have migration files for the models.
2. I did not run the code but it seems to me that the mailings-tab will displayed even if basxconnect.mailer_integration is not installed. Could we change it so that the tab is only visible if the basxconnect.mailer_integration is installed?

**Comment by wipascal** [comment]
1. yup, forgot to add those
2. we need the mailing tab regardless, because there are also mailing preferences that have nothing to do with a mailer. (Briefanrede, Anredeform...)

**Comment by saemideluxe** [comment]
Btw. the CI now seems to be able to run the automated tests without problems. I think because we have now up-to-date pip releases of bread and htmlgenerator.

**Comment by saemideluxe** [comment]
> 1. yup, forgot to add those
> 2. we need the mailing tab regardless, because there are also mailing preferences that have nothing to do with a mailer. (Briefanrede, Anredeform...)

Right, makes sense.

**Review by saemideluxe — APPROVED** [review]
Ok

**Pull request merged**
