### PR TITLE
Refactor/layouts

### PR DESCRIPTION
**Pull request by wipascal**
I tried to break large files and methods into smaller ones. For me it's easier to understand this way. I still find some methods too large, but I had to start somewhere :)

Since I am a complete beginner with Python I appreciate any comments and tips!

### CODE REVIEW

**Comment by saemideluxe** [comment]
That has been overdue since a long time already, thanks!
Refactoring a module (aka "file") to be a package (aka "directory") is exactly the right way to do it when working in python. What I often do keep the same API is importing the identifiers which are used elsewhere into the ```__init__.py``` file. For example:

```python
from .person import editperson_toolbar

__all__ = ["editperson_toolbar"]
```

This way we can still use ```basxconnect.core.layouts.editperson_toolbar``` in all other places instead of having to refactor all pieces where ```editperson_toolbar``` is used (instead of renaming them to ```basxconnect.core.layouts/person.editperson_toolbar```). The above piece of code can also be written the following way which is a bit less pythonic but sometimes helpfull if you have many imports which hight change in the near future (the ```# noqa``` disables the linter from reporting an unused import):

```python
from .person import editperson_toolbar # noqa
```

**Comment by saemideluxe** [comment]
As you can see, the checks are failing. This is because we require all import to be sorted with "Isort" <https://pycqa.github.io/isort/>. Could you install the according plugin in your IDE and update this branch accordingly? Isort should be run with ```isort --profile=black```

**Review by saemideluxe — CHANGES_REQUESTED** [review]
Order imports with isort please.

**Comment by wipascal** [comment]
close accidently

**Comment by wipascal** [comment]
closing this one. opened another one with the desired target branch

**Pull request closed without merging**
