### PR TITLE
add modals for adding and editing addresses

### PR DESCRIPTION
**Pull request by wipascal**
another small step for the UI...

### CODE REVIEW

**Comment by wipascal** [comment]
@saemideluxe I added functionality for configuring the way we parse postal addresses from mailchimp

**Comment by wipascal** [comment]
@saemideluxe will need to add this to the productive UM instance:
`MAILCHIMP_CITY_READER = lambda raw_person: raw_person["merge_fields"].get("MMERGE8", "")
MAILCHIMP_ADDRESS_READER = lambda raw_person: raw_person["merge_fields"].get(
    "MMERGE7", ""
)
MAILCHIMP_ZIP_READER = lambda raw_person: raw_person["merge_fields"].get("MMERGE10", "")
MAILCHIMP_COUNTRY_READER = lambda raw_person: {
    "Switzerland": "CH",
    "Schweiz": "CH",
    "México": "MX",
    "United Kingdom": "UK",
    "Germany": "DE",
    "": "CH",
}.get(raw_person["merge_fields"].get("MMERGE11", ""), "")
`

**Comment by saemideluxe** [comment]
> @saemideluxe will need to add this to the productive UM instance:
> 
> ```
> MAILCHIMP_ADDRESS_READER = lambda raw_person: raw_person["merge_fields"].get(
>     "MMERGE7", ""
> )
> MAILCHIMP_ZIP_READER = lambda raw_person: raw_person["merge_fields"].get("MMERGE10", "")
> MAILCHIMP_COUNTRY_READER = lambda raw_person: {
>     "Switzerland": "CH",
>     "Schweiz": "CH",
>     "México": "MX",
>     "United Kingdom": "UK",
>     "Germany": "DE",
>     "": "CH",
> }.get(raw_person["merge_fields"].get("MMERGE11", ""), "")
> ```
> 
> I know it's ugly but we need to be a bit fast now. And it's only a setting after all...

If it is not something sensitive then we can put it into the base.py settings. Because that file is anyway project specific.

**Review by saemideluxe — APPROVED** [review]
Looks good to me. At some point we should maybe add a description for all the possible settings of each basxconnect and bread module.

**Comment by wipascal** [comment]
> If it is not something sensitive then we can put it into the base.py settings. Because that file is anyway project specific.
that's a good idea, I added it there, so no need for you to update the `local.py`

**Pull request merged**
